[package]
name = "bioutils"
version = "0.1.0"
authors = ["Christopher Sugai <christophersugai@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

unicode-segmentation = "1.7.1"
rand = "0.7.3"
lazy_static = "1.4.0"