[package]
name = "bioutils"
version = "0.1.3"
authors = ["Christopher Sugai <christophersugai@gmail.com>"]
edition = "2018"
description = "A crate containing simple alphabets and utilities for biological sequence data."
license = "MIT OR Apache-2.0"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

unicode-segmentation = "1.7.1"
rand = "0.8.3"
lazy_static = "1.4.0"
url = "2.2.1"
curl = "0.4.34"
